[package]
name = "example-websockets"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.8.0-alpha.1", features = ["ws"] }
axum-extra = { version = "0.10.0-alpha.1", features = ["typed-header"]}
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
headers = "0.4"
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.24.0"
tower-http = { version = "0.6.1", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bin]]
name = "example-websockets"
path = "src/main.rs"

[[bin]]
name = "example-client"
path = "src/client.rs"
